######################################################################
#
# File name : fwrisc_uart_tb_wave.do
# Created on: Thu Jul 18 18:02:05 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
