######################################################################
#
# File name : fwrisc_uart_tb_compile.do
# Created on: Thu Jul 25 19:40:27 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../fwrisc_uart/rtl" "+incdir+../../../../../fwrisc_uart/rtl/uart/vsim/csrc" "+incdir+../../../../fwrisc_uart.srcs/sources_1/ip/clk_wiz_0" \
"../../../../fwrisc_uart.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../fwrisc_uart.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../../fwrisc_uart/rtl" "+incdir+../../../../../fwrisc_uart/rtl/uart/vsim/csrc" "+incdir+../../../../fwrisc_uart.srcs/sources_1/ip/clk_wiz_0" \
"../../../../../fwrisc_uart/rtl/IF_fifo.sv" \
"../../../../../fwrisc_uart/rtl/UART_Registers.sv" \
"../../../../../fwrisc_uart/rtl/UART_baudrate_gen.sv" \
"../../../../../fwrisc_uart/rtl/UART_rx_fsm.sv" \
"../../../../../fwrisc_uart/rtl/UART_tx_fsm.sv" \
"../../../../../fwrisc_uart/rtl/fwrisc.sv" \
"../../../../../fwrisc_uart/rtl/fwrisc_alu.sv" \
"../../../../../fwrisc_uart/rtl/fwrisc_comparator.sv" \
"../../../../../fwrisc_uart/rtl/fwrisc_dbus_if.sv" \
"../../../../../fwrisc_uart/rtl/fwrisc_fpga_top.sv" \
"../../../../../fwrisc_uart/rtl/fwrisc_regfile.sv" \
"../../../../../fwrisc_uart/fpga/fwrisc_uart_wraper.sv" \
"../../../../../fwrisc_uart/rtl/mux2to1.sv" \
"../../../../../fwrisc_uart/rtl/my_fifo.sv" \
"../../../../../fwrisc_uart/rtl/my_ram.sv" \
"../../../../../fwrisc_uart/rtl/uart/op_uart.sv" \
"../../../../../fwrisc_uart/rtl/uart.sv" \
"../../../../../fwrisc_uart/rtl/uart/uart_transceiver.sv" \
"../../../../../fwrisc_uart/rtl/fwrisc_uart_tb.sv" \

# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

