######################################################################
#
# File name : fwrisc_uart_tb_simulate.do
# Created on: Thu Jul 25 19:40:29 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.fwrisc_uart_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {fwrisc_uart_tb_wave.do}

view wave
view structure
view signals

do {fwrisc_uart_tb.udo}

run 1000ns
