######################################################################
#
# File name : pll_tb_wave.do
# Created on: Thu Jul 18 15:44:18 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
