######################################################################
#
# File name : pll_tb_simulate.do
# Created on: Thu Jul 18 18:17:45 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.pll_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {pll_tb_wave.do}

view wave
view structure
view signals

do {pll_tb.udo}

run 1000ns
