######################################################################
#
# File name : simple_ram_tb.udo
# Created on: Sat Jul 27 15:07:51 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
