######################################################################
#
# File name : simple_ram_tb_wave.do
# Created on: Sat Jul 27 15:07:51 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
