######################################################################
#
# File name : simple_ram_tb_compile.do
# Created on: Sat Jul 27 15:10:35 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../fwrisc_uart/rtl" "+incdir+../../../../../fwrisc_uart/rtl/uart/vsim/csrc" "+incdir+../../../../fwrisc_uart.srcs/sources_1/ip/clk_wiz_0" \
"../../../../fwrisc_uart.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../../fwrisc_uart/rtl" "+incdir+../../../../../fwrisc_uart/rtl/uart/vsim/csrc" "+incdir+../../../../fwrisc_uart.srcs/sources_1/ip/clk_wiz_0" \
"../../../../fwrisc_uart.srcs/sim_1/new/simple_ram_tb.v" \


# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

