set_property SRC_FILE_INFO {cfile:D:/Project/16_proj_fwisc_uart/vivado_proj/fwrisc_uart.srcs/constrs_1/new/fwrisc_uart.xdc rfile:../../../fwrisc_uart.srcs/constrs_1/new/fwrisc_uart.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports clock]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports reset]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports program_receiving]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports program_ov]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports program_done]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports tx]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports rx]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -physically_exclusive -group [get_clocks -include_generated_clocks clkfbout_clk_wiz_0] -group [get_clocks -include_generated_clocks clkfbout_clk_wiz_0_1]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -physically_exclusive -group [get_clocks -include_generated_clocks clk_out1_clk_wiz_0] -group [get_clocks -include_generated_clocks clk_out1_clk_wiz_0_1]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_clock_gen/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[5]}]]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[5]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[6]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[7]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[8]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[9]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[10]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[11]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[12]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[13]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[14]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[15]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[16]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[17]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[18]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[19]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[20]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[21]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[22]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[23]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[24]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[25]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[26]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[27]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[28]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[29]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[30]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[31]}]]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[5]}]]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[0]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[1]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[2]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[3]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[4]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[5]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[6]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[7]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[8]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[9]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[10]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[11]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[12]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[13]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[14]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[15]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[16]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[17]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[18]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[19]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[20]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[21]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[22]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[23]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[24]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[25]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[26]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[27]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[28]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[29]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[30]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[31]}]]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[0]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[1]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[2]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[3]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[4]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[5]}]]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[5]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[6]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[7]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[8]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[9]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[10]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[11]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[12]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[13]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[14]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[15]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[16]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[17]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[18]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[19]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[20]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[21]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[22]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[23]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[24]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[25]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[26]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[27]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[28]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[29]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[30]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[31]}]]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list u_fwrisc_fpga_top/dready]]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list u_fwrisc_fpga_top/dvalid]]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list u_fwrisc_fpga_top/dwrite]]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list u_fwrisc_fpga_top/u_core/u_regfile/rd_wen]]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
