set_property SRC_FILE_INFO {cfile:D:/Project/16_proj_fwisc_uart/vivado_proj/fwrisc_uart.srcs/constrs_1/new/fwrisc_uart_xc7v2000t.xdc rfile:../../../fwrisc_uart.srcs/constrs_1/new/fwrisc_uart_xc7v2000t.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS18} [get_ports clock]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L34 IOSTANDARD LVCMOS18} [get_ports reset]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS18} [get_ports program_receiving]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS18} [get_ports program_ov]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M34 IOSTANDARD LVCMOS18} [get_ports program_done]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J8 IOSTANDARD LVCMOS18} [get_ports tx]; #J8 IO_0_VRN_39 <--u1 | u217--> IO_L2N_18 M6
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS18} [get_ports rx]; #T10 IO_0_VRN_37 <--u1 | u217--> IO_L0P_18 K5
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_clock_gen/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[0]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[1]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[2]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[3]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[4]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[5]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[6]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[7]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[8]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[9]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[10]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[11]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[12]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[13]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[14]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[15]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[16]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[17]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[18]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[19]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[20]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[21]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[22]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[23]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[24]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[25]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[26]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[27]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[28]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[29]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[30]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_rdata[31]}]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[5]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[6]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[7]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[8]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[9]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[10]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[11]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[12]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[13]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[14]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[15]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[16]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[17]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[18]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[19]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[20]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[21]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[22]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[23]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[24]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[25]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[26]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[27]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[28]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[29]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[30]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_rdata[31]}]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rb_raddr[5]}]]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_waddr[5]}]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[0]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[1]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[2]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[3]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[4]} {u_fwrisc_fpga_top/u_core/u_regfile/ra_raddr[5]}]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[0]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[1]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[2]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[3]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[4]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[5]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[6]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[7]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[8]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[9]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[10]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[11]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[12]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[13]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[14]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[15]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[16]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[17]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[18]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[19]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[20]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[21]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[22]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[23]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[24]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[25]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[26]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[27]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[28]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[29]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[30]} {u_fwrisc_fpga_top/u_core/u_regfile/rd_wdata[31]}]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list u_fwrisc_fpga_top/dready]]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list u_fwrisc_fpga_top/dvalid]]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list u_fwrisc_fpga_top/dwrite]]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list u_fwrisc_fpga_top/u_core/u_regfile/rd_wen]]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list rx_IBUF]]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list tx_OBUF]]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
